server:
  port: 8080
spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/event-app
#    username: tekpor
#    password: tekporpassword
  jpa:
    properties:
      hibernate:
        ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
file:
  upload:
    queue: file-upload-queue
s3:
  s3bucket:
    key: thisismykey
    bucketName: bucketName

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

graphql:
  servlet:
    mapping: "/graphql"
    enabled: true
    exception-handlers-enabled: true
    corsEnabled: true
  graphiql:
    mapping: graphiql
    enabled: true